apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store
  labels:
    app: book-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
      - name: book-store
        image: book-store
        # This is just to make sure that we get the image from local docker instead of trying to pull latest from public docker.
        imagePullPolicy: Never
        ports:
        - containerPort: 8085